### ISSUE TITLE
Not recognizing installed tableausdk 

### ISSUE THREAD

**Issue by aawiegel** [bwiley1/pandleau#10]
When installing the package from pip or by running setup.py with python, it looks for the tableausdk via pip and cannot find it. (I already installed the extract api and verified that it correctly installed by importing it in Python.) I was able to install it by running setup.py and removing the reference to tableausdk. I then tested it by converting a data frame to a .hyper file and it worked fine.

Unrelated issue, but just a heads up that infer_dtypes in the pandas api was new in version 0.21.0, so this package won't work with earlier versions of pandas.

**Comment by bwiley1** [comment]
Hi aawiegel,

Thanks for highlighting this issue. Tableau hasn't added tableausdk to the PiPy site, so that's why pip is unable to find it - you have to download it separately (see the home page for instructions on this part). A good update to this package might be removing the reference to tableausdk during setup, as you did above, so that users don't get the error message that you did. I'll make a note of this and see what I can do when I get a spare moment from studying for this upcoming actuary exam XD

Good note on the infer_dtypes functionality - I'll be sure to add that to the instructions on the homepage. If you have any other observations for improvements, feel free to fork the repo and I'd be happy to collaborate with you. Thanks!

Best,
jamin4lyfe

**Comment by aawiegel** [comment]
Wow, thanks for the fast response. I think that's a pretty easy work around for now; I'll also complain on the tableau sdk forums about the lack of a pip installable tableausdk. :)

Some quick digging into different versions of pandas suggests that if the pandas version is lower, `pd.lib.infer_dtype(column)` should work instead. Weirdly, this method is not documented anywhere I could find.

I can fork the repo and test that these changes work on my own stuff. (We use a VM where because of weird compatibility issues, we have to use an old version of pandas.)
